" Spaces insted of tabs
" You could use :retab
set tabstop=4       " Number of spaces that a <Tab> counts for
set shiftwidth=4    " Number of spaces to use for each step of (auto)indent
set expandtab

" Show hiden symbols
" autocmd BufWinEnter <buffer> match Error /\s\+$/  
set list
nnoremap <Leader><F12> :set list!<CR>
set listchars=tab:>-,extends:>,precedes:<,space:·
" Dumb Netrw flag to move and copy
" https://vonheikemen.github.io/devlog/tools/using-netrw-vim-builtin-file-explorer/
let g:netrw_keepdir = 0
" Line number on the left
set rnu
set nu
" Enable file type detection
filetype plugin on
" Set up completion options
set completeopt=menuone,noinsert,noselect
" See pressed key
set showcmd
" External configs 
"" Thirdparty (stolen) ideas
source ~/.vim/thirdpartyideas.vim
"" Plug manager
source ~/.vim/plugconf.vim
"" Gomode
source ~/.vim/goconf.vim
"" Keybindings
source ~/.vim/keybindings.vim
source ~/.vim/fzfkeymappings.vim
