" Spaces insted of tabs
" You could use :retab
set tabstop=4       " Number of spaces that a <Tab> counts for
set shiftwidth=4    " Number of spaces to use for each step of (auto)indent
set expandtab

" Use tabs for Go files
autocmd FileType go setlocal noexpandtab

" Show hiden symbols
" autocmd BufWinEnter <buffer> match Error /\s\+$/  
set list
nnoremap <F12> :set list!<CR>
set listchars=tab:>-,extends:>,precedes:<,space:·

" Dumb Netrw flag to move and copy
" https://vonheikemen.github.io/devlog/tools/using-netrw-vim-builtin-file-explorer/
let g:netrw_keepdir = 0

" Line number on the left
set rnu
set nu

" Enable file type detection
filetype plugin on

" Set up completion options
set completeopt=menuone,noinsert,noselect

" Use Tab for completion
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" External configs 
"" Plug manager
source ~/.vim/plugconf.vim
"" Tab config
source ~/.vim/window.vim
