return {
  { "nvim-tree/nvim-tree.lua", enabled = false },
  { "nvim-telescope/telescope-fzf-native.nvim", enabled = false },
  { "nvim-treesitter/nvim-treesitter", enabled = false },
  --{ "folke/which-key.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "mason-org/mason-lspconfig.nvim", enabled = false },
  { "mason-org/mason.nvim", enabled = false },
  { "nvim-mini/mini.pairs", enabled = false },
  { "MunifTanjim/nui.nvim", enabled = false },
  { "mfussenegger/nvim-lint", enabled = false },
  { "neovim/nvim-lspconfig", enabled = false },
  { "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },
  { "windwp/nvim-ts-autotag", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "folke/ts-comments.nvim", enabled = false },
  { "folke/lazydev.nvim", enabled = false },
  { "saghen/blink.cmp", enabled = false },
  { "stevearc/conform.nvim", enabled = false },
}
