# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# Timeout to keystrokes
KEYTIMEOUT=1
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '~/.zshrc'
autoload -Uz compinit
compinit
# End of lines added by compinstall

# Aliases
alias ls='ls --color'
alias ll='ls --color -lA --group-directories-first'
alias :q='exit'
# Add go path
path+=('/usr/lib/go-1.23/bin/')
path+=('~/go/bin/')
# PROMPT
source "$HOME/.config/zsh/prompt.zsh"

